Teensy decode
vt-sailbot/arduino-sailbot-20 pull request #6
Opened 2021-03-29 15:17 UTC by Pworks3

Functionality to read the pulse width of the PWM signals from the receiver.

2021-04-01 01:27 UTC, evallen requested changes
Looks really good so far!
I left a couple of comments throughout, but I like the structure overall.

A few more things I think we should do before finishing this off:
1. Write a central README.md that explains all of this and how it works - focusing specifically on the purpose of these files, how they work (using interrupts), and especially how to use them. 
2. Write some tests. Normally I'd want automated tests, but that's a bit difficult with hardware - instead, I think a set of test procedures would be good.
  * Things like "move the left stick all the way to the left. You should get XXX value." and stuff like that - basically a formalized version of your own testing process. 

Looking forward to merging this!

2021-04-01 01:27 UTC, evallen commented on main/pwm_channel.ino
> +
I think it would be useful to put a small block comment here explaining some of the design decisions here, such as:
1. Why we have to attach a new interrupt on every interrupt
2. Why we chose to record the pwmValue _on each fall interrupt_ instead of recording the fall time (and risking the occasional mishap where we try to calculate the pwmValue between the rise and fall).

2021-04-01 01:27 UTC, evallen commented on main/pwm_channel.h
> +struct pwmChannel
Maybe add a small blurb about how to use the pwmChannel struct  (or how _not_ to use it) - (do I have to set it up? should I ever explicitly touch any of its members? do I need to update pwmValue, or does it happen automatically? how? [interrupts] etc.).

2021-04-01 12:30 UTC, Pworks3 commented on main/pwm_channel.h
> +struct pwmChannel
Sounds good, I'll write some comments within the code and add a readme to the branch that will contain more detailed instructions .

2021-04-05 03:12 UTC, evallen commented on main/pwm_channel.h
> +struct pwmChannel
Comments look good so far! They give useful details on how to use the structs / functions and why they're like that. I think the README should focus more on the high-level design (how we're using interrupts overall, why, etc.).

2021-04-05 14:52 UTC, Pworks3 commented on main/pwm_channel.h
> +struct pwmChannel
That's what I had planned with it. Going to try and work on it today and get the majority of it done, got a midterm and a project though so we will see how that goes.

2021-04-12 00:35 UTC, Pworks3 commented
Going to add the section on testing in the README tomorrow when I have the readings from the scope. Then explain a general process of how one would go about testing with a different RC receiver to ensure everything still holds.

2021-04-15 01:09 UTC, evallen approved these changes

2021-04-15 01:10 UTC, merged